quartz()
plot(epcc$Sub_metering_1,type="l",ylab="Energy sub metering",xlab="",xaxt="n")
lines(epcc$Sub_metering_2,type="l",col="red")
lines(epcc$Sub_metering_3,type="l",col="blue")
axis(1,at=c(1,1440,2880),label=c("Thursday","Friday","Saturday"))
legend("topright",pch="-",col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.copy(png,file="plot3.png",width=480,height=480)
dev.cur()
